const Data = [
  {
    id: 1,
    img: require("./images/img (1).png"),
    nombre: "UrbanGlide",
    desc: "Un estilo moderno para la vida urbana, estas zapatillas ofrecen un equilibrio perfecto entre moda y funcionalidad.",
    precio: 56,
    categoria: "URBAN",
    stock: 8,
  },
  {
    id: 2,
    img: require("./images/img (2).png"),
    nombre: "BreezeEase",
    desc: "La ligereza y la frescura se encuentran en estas chinelas, perfectas para relajarse con estilo en días cálidos.",
    precio: 52,
    categoria: "RELAX",
    stock: 4,
  },
  {
    id: 3,
    img: require("./images/img (3).png"),
    nombre: "SkyStride",
    desc: "Zapatillas diseñadas para una sensación ligera y una pisada suave, inspiradas en la libertad y la comodidad.",
    precio: 68,
    categoria: "URBAN",
    stock: 6,
  },
  {
    id: 4,
    img: require("./images/img (4).png"),
    nombre: "VelvetVista H2",
    desc: "Elegantes y suaves al tacto, estas chinelas de terciopelo son una declaración de estilo para tus momentos de relajación en casa.",
    precio: 38,
    categoria: "RELAX",
    stock: 3,
  },
  {
    id: 5,
    img: require("./images/img (5).png"),
    nombre: "MoonMist",
    desc: "Sumérgete en la suavidad de la luna con estas chinelas que te envuelven en una sensación de comodidad celestial.",
    precio: 32,
    categoria: "RELAX",
    stock: 3,
  },
  {
    id: 6,
    img: require("./images/img (6).png"),
    nombre: "SunSoles",
    desc: "Diseñadas para abrazar tus pies con comodidad, estas chinelas son el complemento perfecto para disfrutar del sol y la serenidad.",
    precio: 18,
    categoria: "RELAX",
    stock: 4,
  },
  {
    id: 7,
    img: require("./images/img (7).png"),
    nombre: "CushyCloud",
    desc: "Pisa suavemente con estas chinelas que ofrecen una sensación de caminar sobre nubes gracias a su acolchado mullido.",
    precio: 35,
    categoria: "RELAX",
    stock: 10,
  },
  {
    id: 8,
    img: require("./images/img (8).png"),
    nombre: "HarborHug",
    desc: "Inspiradas en la tranquilidad de los puertos, estas chinelas envuelven tus pies con una sensación de seguridad y suavidad.",
    precio: 25,
    categoria: "RELAX",
    stock: 7,
  },
  {
    id: 9,
    img: require("./images/img (9).png"),
    nombre: "WhisperWalk",
    desc: "Camina en silencio con estas chinelas que combinan ligereza y suavidad para una experiencia de descanso sin igual.",
    precio: 30,
    categoria: "RELAX",
    stock: 3,
  },
  {
    id: 10,
    img: require("./images/img (10).png"),
    nombre: "VelvetVista",
    desc: "Elegantes y suaves al tacto, estas chinelas de terciopelo son una declaración de estilo para tus momentos de relajación en casa.",
    precio: 32,
    categoria: "RELAX",
    stock: 3,
  },
  {
    id: 11,
    img: require("./images/img (11).png"),
    nombre: "MeadowMingle",
    desc: "Inspiradas en prados tranquilos, estas chinelas son perfectas para un relajado paseo por la naturaleza, incluso si es solo en casa.",
    precio: 14,
    categoria: "RELAX",
    stock: 2,
  },
  {
    id: 12,
    img: require("./images/img (12).png"),
    nombre: "GlideGentle",
    desc: "Deslízate suavemente por tus momentos de relajación con estas chinelas que combinan elegancia y comodidad en cada paso.",
    precio: 48,
    categoria: "RELAX",
    stock: 12,
  },
  {
    id: 13,
    img: require("./images/img (13).png"),
    nombre: "VelvetVibe",
    desc: "Suaves al tacto y elegantes en el diseño, estas zapatillas ofrecen una experiencia lujosa para tus pies.",
    precio: 50,
    categoria: "URBAN",
    stock: 6,
  },
  {
    id: 14,
    img: require("./images/img (14).png"),
    nombre: "SwiftFlex",
    desc: "Con su suela flexible y ajuste ceñido, estas zapatillas son ideales para movimientos rápidos y actividades dinámicas.",
    precio: 56,
    categoria: "URBAN",
    stock: 2,
  },
  {
    id: 15,
    img: require("./images/img (15).png"),
    nombre: "EchoRush",
    desc: "La combinación de velocidad y resistencia, estas zapatillas te impulsarán hacia adelante con cada paso.",
    precio: 90,
    categoria: "URBAN",
    stock: 6,
  },
  {
    id: 16,
    img: require("./images/img (16).png"),
    nombre: "NeoBurst",
    desc: "Un estallido de innovación en cada paso, estas zapatillas incorporan tecnología avanzada para un rendimiento excepcional.",
    precio: 100,
    categoria: "URBAN",
    stock: 3,
  },
  {
    id: 17,
    img: require("./images/img (17).png"),
    nombre: "CitySculpt Classic",
    desc: "Un modelo exclusivo que rinde homenaje a la esencia urbana con un diseño clásico, ofreciendo estilo atemporal y comodidad en cada paso.",
    precio: 153,
    categoria: "EXCLUSIVE",
    stock: 4,
  },
  {
    id: 18,
    img: require("./images/img (18).png"),
    nombre: "StridePro",
    desc: "Un modelo exclusivo que combina rendimiento y estilo, ofreciendo una zapatilla deportiva única para aquellos que buscan destacar en su actividad física con elegancia.",
    precio: 185,
    categoria: "EXCLUSIVE",
    stock: 2,
  },
  {
    id: 19,
    img: require("./images/img (19).png"),
    nombre: "EcoSprint",
    desc: "Un paso hacia un futuro sostenible, estas zapatillas están hechas con materiales ecológicos sin comprometer el estilo ni el rendimiento.",
    precio: 83,
    categoria: "URBAN",
    stock: 12,
  },
  {
    id: 20,
    img: require("./images/img (20).png"),
    nombre: "PulseDrive Urban",
    desc: "Diseñadas para la pulsante vida urbana, estas zapatillas aportan un impulso extra a tu estilo diario con una combinación de moda y funcionalidad.",
    precio: 55,
    categoria: "URBAN",
    stock: 8,
  },
  {
    id: 21,
    img: require("./images/img (21).png"),
    nombre: "RetroFlex",
    desc: "Un guiño al pasado con un toque moderno, estas zapatillas combinan la nostalgia con las últimas tendencias.",
    precio: 60,
    categoria: "URBAN",
    stock: 3,
  },
  {
    id: 22,
    img: require("./images/img (22).png"),
    nombre: "BreezeWalk X1",
    desc: "Este modelo exclusivo lleva el estilo urbano a una nueva dimensión, fusionando innovación y elegancia para aquellos que buscan destacar con un toque moderno.",
    precio: 42,
    categoria: "URBAN",
    stock: 3,
  },
  {
    id: 23,
    img: require("./images/img (23).png"),
    nombre: " UrbanNova",
    desc: "Este modelo exclusivo lleva el estilo urbano a una nueva dimensión, fusionando innovación y elegancia para aquellos que buscan destacar con un toque moderno.",
    precio: 40,
    categoria: "URBAN",
    stock: 6,
  },
  {
    id: 24,
    img: require("./images/img (24).png"),
    nombre: "TimeWarp",
    desc: ".Un modelo que te transporta en el tiempo, estas zapatillas capturan la esencia de una época pasada con un diseño que evoca nostalgia y estilo atemporal.",
    precio: 130,
    categoria: "EXCLUSIVE",
    stock: 3,
  },
  {
    id: 25,
    img: require("./images/img (25).png"),
    nombre: "ZenithFlex",
    desc: "Alcanza nuevas alturas con estas zapatillas que ofrecen una flexibilidad excepcional y un diseño profesional para tus entrenamientos más exigentes.",
    precio: 56,
    categoria: "URBAN",
    stock: 8,
  },
  {
    id: 26,
    img: require("./images/img (26).png"),
    nombre: "PowerPace X",
    desc: "Diseñadas para la máxima potencia y velocidad, estas zapatillas proporcionan un impulso extra para tus sesiones de entrenamiento más intensas.",
    precio: 70,
    categoria: "URBAN",
    stock: 4,
  },
  {
    id: 27,
    img: require("./images/img (27).png"),
    nombre: "DynamicStride Pro",
    desc: "Un modelo de alto rendimiento que se adapta a tus movimientos dinámicos, ofreciendo comodidad y soporte durante tus actividades deportivas.",
    precio: 100,
    categoria: "URBAN",
    stock: 3,
  },
];

export default Data;
